#!/usr/bin/env python3
"""Copy inference-only cluster_forecast modules into the backend package.

Run from repo root or train_model/:
    python scripts/sync_inference_to_backend.py

Rewrites imports for ``predictor.*`` and adds a generated facade
``predictor/cluster_forecast.py``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TRAIN_SRC = Path(__file__).resolve().parent.parent / "src" / "cluster_forecast"
BACKEND_FORECASTING = (
    Path(__file__).resolve().parent.parent.parent
    / "backend"
    / "src"
    / "predictor"
    / "forecasting"
)
BACKEND_FACADE = BACKEND_FORECASTING.parent / "cluster_forecast.py"

# Relative paths under cluster_forecast/ to sync (inference stack).
SYNC_PATHS = [
    "config.py",
    "metrics.py",
    "intervals.py",
    "features.py",
    "models/seasonal_naive.py",
    "models/holt_winters.py",
    "inference.py",
]

IMPORT_REWRITES = [
    (re.compile(r"^from air_quality_config import"), "from predictor.air_quality_config import"),
    (re.compile(r"^from cluster_forecast\."), "from predictor.forecasting."),
]


def transform_source(text: str) -> str:
    lines = []
    for line in text.splitlines(keepends=True):
        out = line
        for pattern, repl in IMPORT_REWRITES:
            out = pattern.sub(repl, out)
        lines.append(out)
    return "".join(lines)


def sync_file(rel_path: str) -> None:
    src = TRAIN_SRC / rel_path
    dst = BACKEND_FORECASTING / rel_path
    dst.parent.mkdir(parents=True, exist_ok=True)
    raw = src.read_text(encoding="utf-8")
    dst.write_text(transform_source(raw), encoding="utf-8")
    print(f"  {rel_path}")


def write_backend_models_init() -> None:
    """Inference-only models package (no lag.py on backend)."""
    path = BACKEND_FORECASTING / "models" / "__init__.py"
    path.write_text(
        '"""Inference model families (generated; no training-only lag models)."""\n\n'
        "from predictor.forecasting.models.holt_winters import (\n"
        "    holt_winters_forecast_from_submodels,\n"
        "    holt_winters_vector_forecast,\n"
        ")\n"
        "from predictor.forecasting.models.seasonal_naive import (\n"
        "    seasonal_naive_vector_forecast,\n"
        ")\n\n"
        "__all__ = [\n"
        '    "holt_winters_forecast_from_submodels",\n'
        '    "holt_winters_vector_forecast",\n'
        '    "seasonal_naive_vector_forecast",\n'
        "]\n",
        encoding="utf-8",
    )
    print("  models/__init__.py (generated)")


def write_backend_init() -> None:
    init_path = BACKEND_FORECASTING / "__init__.py"
    init_path.write_text(
        '"""Synced inference modules (generated by sync_inference_to_backend.py)."""\n\n'
        "from predictor.forecasting.inference import forecast_from_artifact, history_from_artifact\n\n"
        '__all__ = ["forecast_from_artifact", "history_from_artifact"]\n',
        encoding="utf-8",
    )
    print("  __init__.py")


def write_facade() -> None:
    BACKEND_FACADE.write_text(
        '"""API inference facade — DO NOT EDIT; run train_model/scripts/sync_inference_to_backend.py."""\n\n'
        "from predictor.forecasting.inference import forecast_from_artifact, history_from_artifact\n\n"
        '__all__ = ["forecast_from_artifact", "history_from_artifact"]\n',
        encoding="utf-8",
    )
    rel = BACKEND_FACADE.relative_to(BACKEND_FORECASTING.parent.parent.parent)
    print(f"  -> {rel}")


def remove_stale_backend_files() -> None:
    """Drop files no longer part of the inference sync set."""
    stale = BACKEND_FORECASTING / "artifacts.py"
    if stale.is_file():
        stale.unlink()
        print("  removed stale artifacts.py")


def main() -> int:
    if not TRAIN_SRC.is_dir():
        print(f"Missing source package: {TRAIN_SRC}", file=sys.stderr)
        return 1
    print(f"Sync {TRAIN_SRC.name}/ -> {BACKEND_FORECASTING}")
    remove_stale_backend_files()
    for rel in SYNC_PATHS:
        if not (TRAIN_SRC / rel).is_file():
            print(f"Missing: {rel}", file=sys.stderr)
            return 1
        sync_file(rel)
    write_backend_models_init()
    write_backend_init()
    write_facade()
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
